# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'a.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from qfluentwidgets import BodyLabel, CaptionLabel, LineEdit, ProgressBar, PushButton


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(409, 265)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(5, 5, 401, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.BodyLabel = BodyLabel(self.verticalLayoutWidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_9.addWidget(self.BodyLabel)
        self.LineEdit = LineEdit(self.verticalLayoutWidget)
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout_9.addWidget(self.LineEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.xz = PushButton(self.verticalLayoutWidget)
        self.xz.setMinimumSize(QtCore.QSize(0, 50))
        self.xz.setObjectName("xz")
        self.horizontalLayout_10.addWidget(self.xz)
        self.qk = PushButton(self.verticalLayoutWidget)
        self.qk.setMinimumSize(QtCore.QSize(0, 50))
        self.qk.setObjectName("qk")
        self.horizontalLayout_10.addWidget(self.qk)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.small = CaptionLabel(self.verticalLayoutWidget)
        self.small.setMinimumSize(QtCore.QSize(0, 0))
        self.small.setObjectName("small")
        self.horizontalLayout_8.addWidget(self.small)
        self.jdt = ProgressBar(self.verticalLayoutWidget)
        self.jdt.setMinimumSize(QtCore.QSize(0, 16))
        self.jdt.setMouseTracking(False)
        self.jdt.setMinimum(0)
        self.jdt.setProperty("value", 0)
        self.jdt.setTextVisible(True)
        self.jdt.setObjectName("jdt")
        self.horizontalLayout_8.addWidget(self.jdt)
        self.max = CaptionLabel(self.verticalLayoutWidget)
        self.max.setObjectName("max")
        self.horizontalLayout_8.addWidget(self.max)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.retranslateUi(Form)
        
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "下崽器"))
        self.BodyLabel.setText(_translate("Form", "下载链接"))
        self.xz.setText(_translate("Form", "下载"))
        self.qk.setText(_translate("Form", "清空"))
        self.small.setText(_translate("Form", "0"))
        self.max.setText(_translate("Form", "0"))


